### ISSUE TITLE
NoMethodError in sessions#create

### ISSUE THREAD

**Issue by Mitcheljager** [EloHellEsports/workshop.codes#128]
## Error in workshop-codes

**NoMethodError** in **sessions#create**
undefined method `linked_id' for nil:NilClass

[View on Bugsnag](https://app.bugsnag.com/workshop-codes/workshop-codes/errors/623d27477254e200085fd60c?event_id=623d37c90092f463c5e10000&i=gh&m=ci)

## Stacktrace

    app/controllers/sessions_controller.rb:87 - link_user
    app/controllers/sessions_controller.rb:18 - create
    app/controllers/application_controller.rb:50 - set_current_user

[View full stacktrace](https://app.bugsnag.com/workshop-codes/workshop-codes/errors/623d27477254e200085fd60c?event_id=623d37c90092f463c5e10000&i=gh&m=ci)

*Created by mitchel_jager@hotmail.com via Bugsnag*

**Comment by CactusPuppy** [comment]
Closed by #129
