### ISSUE TITLE
ActionView::Template::Error in profiles#show

### ISSUE THREAD

**Issue by Mitcheljager** [EloHellEsports/workshop.codes#169]
## Error in workshop-codes

**ActionView::Template::Error** in **profiles#show**
Tried to load unspecified class: ActionController::Parameters

[View on Bugsnag](https://app.bugsnag.com/workshop-codes/workshop-codes/errors/62de2eb4ceec70000868b9a3?event_id=62de859d009548978bc80000&i=gh&m=ci)

## Stacktrace

    app/helpers/blocks_helper.rb:3 - block_property
    app/views/blocks/profile/_highlight.html.erb:1 - _app_views_blocks_profile__highlight_html_erb___4504466060286577200_87860
    app/views/profiles/show.html.erb:27 - block in _app_views_profiles_show_html_erb__777682095479927505_87220
    app/views/profiles/show.html.erb:25 - _app_views_profiles_show_html_erb__777682095479927505_87220
    app/controllers/application_controller.rb:61 - set_current_user

[View full stacktrace](https://app.bugsnag.com/workshop-codes/workshop-codes/errors/62de2eb4ceec70000868b9a3?event_id=62de859d009548978bc80000&i=gh&m=ci)

*Created by mitchel_jager@hotmail.com via Bugsnag*

**Comment by CactusPuppy** [comment]
Closed in 21e4bf38d11d938217d80a69cf5945ef93a7c772

**Comment by Mitcheljager** [comment]
An error linked to this issue has been marked as fixed in Bugsnag
[**ActionView::Template::Error** in **profiles#show**](https://app.bugsnag.com/workshop-codes/workshop-codes/errors/62de2eb4ceec70000868b9a3?event_id=62dec8670095515dbdb60000&i=gh&m=fx)
