### ISSUE TITLE
ActionController::BadRequest in GET /search

### ISSUE THREAD

**Issue by Mitcheljager** [EloHellEsports/workshop.codes#180]
## Error in workshop-codes

**ActionController::BadRequest** in **GET /search**
Invalid query parameters: invalid %-encoding (500%)

[View on Bugsnag](https://app.bugsnag.com/workshop-codes/workshop-codes/errors/62e95edfb1e808000864bb6d?event_id=62efdf81009617c4e1d40000&i=gh&m=ci)

## Stacktrace

    vendor/ruby-3.0.0/lib/ruby/3.0.0/uri/common.rb:324 - decode_www_form_component

[View full stacktrace](https://app.bugsnag.com/workshop-codes/workshop-codes/errors/62e95edfb1e808000864bb6d?event_id=62efdf81009617c4e1d40000&i=gh&m=ci)

*Created by mitchel_jager@hotmail.com via Bugsnag*

**Comment by CactusPuppy** [comment]
This is due to the search box not properly encoding its contents

**Comment by Mitcheljager** [comment]
An error linked to this issue has been marked as fixed in Bugsnag
[**ActionController::BadRequest** in **GET /search**](https://app.bugsnag.com/workshop-codes/workshop-codes/errors/62e95edfb1e808000864bb6d?event_id=62f57e640096016ed84c0000&i=gh&m=fx)
