### ISSUE TITLE
UI permits Comment button to be pressed even when no comment is provided

### ISSUE THREAD

**Issue by Mitcheljager** [EloHellEsports/workshop.codes#181]
## Error in workshop-codes

**ArgumentError** in **comments#create**
too few arguments

[View on Bugsnag](https://app.bugsnag.com/workshop-codes/workshop-codes/errors/62e41f2fb238490008a44b25?event_id=62f17a68009619a8f8350000&i=gh&m=ci)

## Stacktrace

    app/controllers/comments_controller.rb:40 - format
    app/controllers/comments_controller.rb:40 - create
    app/controllers/application_controller.rb:61 - set_current_user

[View full stacktrace](https://app.bugsnag.com/workshop-codes/workshop-codes/errors/62e41f2fb238490008a44b25?event_id=62f17a68009619a8f8350000&i=gh&m=ci)

*Created by mitchel_jager@hotmail.com via Bugsnag*

**Comment by CactusPuppy** [comment]
Closed in #186

**Comment by Mitcheljager** [comment]
An error linked to this issue has been marked as fixed in Bugsnag
[**ArgumentError** in **comments#create**](https://app.bugsnag.com/workshop-codes/workshop-codes/errors/62e41f2fb238490008a44b25?event_id=62f5b6de0096204556310000&i=gh&m=fx)
