### ISSUE TITLE
[Feature Request] Apply filters on search

### ISSUE THREAD

**Issue by xathon** [EloHellEsports/workshop.codes#37]
It would be great if any selected filters would be applied automatically on clicking the search button, without the need to click the Apply Filter button. In the current state, you basically have two search buttons, one for just searching text and one for searching with filters, I believe that this could be combined into one button; entering nothing into the search bar but setting a filter and pressing Search could basically do what the Apply Filter button does now, if you don't want to search for a name but for a mode type.

**Comment by Mitcheljager** [comment]
I could have sworn that was the case already, but you're right, it's not. I will add this!

**Comment by Mitcheljager** [comment]
Fixed with https://github.com/EloHellEsports/workshop.codes/commit/b5d0a00619e3d5be1e0fa7a012436ba58603e161
